# Generated by Django 2.1.5 on 2019-01-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('publish_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Blogcon',
            fields=[
                ('machine_room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('use', models.CharField(max_length=20, verbose_name='用途')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('head', models.CharField(max_length=20, verbose_name='负责人')),
                ('type', models.CharField(max_length=20, verbose_name='型号')),
                ('memory', models.CharField(max_length=20, verbose_name='内存')),
                ('cpu', models.CharField(max_length=20, verbose_name='cpu')),
                ('cipan', models.CharField(max_length=20, verbose_name='cpu')),
                ('operating', models.CharField(max_length=20, verbose_name='操作系统')),
                ('belonghouse', models.CharField(max_length=20, verbose_name='所属机房')),
                ('belonggroup', models.CharField(max_length=20, verbose_name='所属组')),
                ('sblogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo01.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('gdate', models.DateField()),
                ('ggirlnum', models.IntegerField()),
                ('gboynum', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sgender', models.BooleanField(default=True)),
                ('sage', models.IntegerField()),
                ('scontend', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('sgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo01.Grades')),
            ],
        ),
    ]
